name: Run Tests on Pull Request

on:
    pull_request:
        branches:
            - main
        # This will run the tests whenever a PR is created or updated

jobs:
    test:
        runs-on: ubuntu-latest # Runs on an Ubuntu runner

        steps:
            - name: Checkout code
              uses: actions/checkout@v3 # Checkout the PR branch

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12" # Specify the Python version you want to use

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt  # Install the dependencies

            - name: Run tests
              run: |
                  python -m unittest discover django_react_jollof/tests  # Run your tests
